[package]
name = "dyn-ip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.46.0"
aws-sdk-route53 = "0.16.0"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"
thiserror = "1"
uuid = { version = "1.1.2", features = ["v4"] }
addr = "0.15.4"
