name: Publish Docker image
on:
  release:
    types: [ created ]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
    uses: docker/login-action@v1
    with:
    registry: ghcr.io
    username: ${{ github.actor }}
    password: ${{ secrets.GITHUB_TOKEN }}
                - name: Build the dyn-ip Docker image
    run: |
      docker build . --tag ghcr.io/Krakaw/dyn-ip:latest
      docker push ghcr.io/Krakaw/dyn-ip:latest