name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags, e.g., v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - "x86_64-unknown-linux-gnu"    # Normal version
          - "x86_64-unknown-linux-musl"   # Compatibility version
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Add Musl Target for Compatibility
        if: ${{ matrix.target == 'x86_64-unknown-linux-musl' }}
        run: rustup target add x86_64-unknown-linux-musl

      - name: Install Dependencies for Musl
        if: ${{ matrix.target == 'x86_64-unknown-linux-musl' }}
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Build Binary
        run: |
          mkdir -p dist
          cargo build --release --target ${{ matrix.target }}
          cp target/${{ matrix.target }}/release/dyn-ip dist/dyn-ip-${{ matrix.target }}

      - name: Debug -List Files After Build
        run: ls -lR

      - name: Upload Binary (Normal)
        if: ${{ matrix.target == 'x86_64-unknown-linux-gnu' }}
        uses: actions/upload-artifact@v4
        with:
          name: dyn-ip-x86_64-unknown-linux-gnu
          path: dist/dyn-ip-x86_64-unknown-linux-gnu

      - name: Upload Binary (Compatibility)
        if: ${{ matrix.target == 'x86_64-unknown-linux-musl' }}
        uses: actions/upload-artifact@v4
        with:
          name: dyn-ip-x86_64-unknown-linux-musl
          path: dist/dyn-ip-x86_64-unknown-linux-musl

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download All Binaries
        uses: actions/download-artifact@v3
        with:
          name: dyn-ip-x86_64-unknown-linux-gnu

      - name: Download Compatibility Binary
        uses: actions/download-artifact@v3
        with:
          name: dyn-ip-x86_64-unknown-linux-musl

      - name: Debug -List Downloaded Files
        run: ls -l

      - name: Ensure Dist Directory and Move Files
        run: |
          mkdir -p dist
          mv dyn-ip-x86_64-unknown-linux-gnu dist/
          mv dyn-ip-x86_64-unknown-linux-musl dist/

      - name: Debug -List Files in Dist
        run: ls -l dist

      - name: Debug -Check Working Directory
        run: pwd

      - name: Debug -List All Files Recursively
        run: ls -lR

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/dyn-ip-x86_64-unknown-linux-gnu
            dist/dyn-ip-x86_64-unknown-linux-musl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
